#!/bin/sh
usage() { echo "Usage: $0 [-u <username>] [-t <repo|gist>] [-n <string>] (opt. [-p <true|false>] [-d <description>] [-h <homepage>] [-g <gitignore>] [-i <true|false>]) [filename]" 1>&2; exit 1; }

while getopts ":u:t:n:p:d:h:g:i:" o; do
  case "${o}" in
    u)
      u=${OPTARG}
      ;;
    t)
      t=${OPTARG}
      ((t == "repo" || t == "gist")) || usage
      ;;
    n)
      n=${OPTARG}
      ;;
    p)
      p=${OPTARG}
      ((p == true || p == false)) || usage
      ;;
    d)  
      d=${OPTARG} || "Created via API"
      ;;
    h)  
      h=${OPTARG}
      ;;
    g)  
      g=${OPTARG}
      ;;
    i)
      i=${OPTARG}
      ((i == true || i == false)) || usage
      ;;
    *)
      usage
      ;;
  esac
done
shift $((OPTIND-1))

if [ -z "${u}" ] || [ -z "${t}" ] || [ -z "${n}" ]; then
    usage
  else
    url=https://api.github.com

    case "$t" in
      'repo') 
        if [ -z "${p}" ]
          then 
            p=false
        fi

        if [ -z "${i}" ]
          then 
            i=false
        fi
        homepage="${h}" || ' '

        file=$1
        # echo $file
        /usr/bin/curl --request POST $url/user/repos --user $u --data '{"name": "'$n'","description": "'$d'","homepage": "'$h'","private":'${p}', "gitignore_template":"'${g}'", "auto_init":"'${i}'"}'
        /usr/bin/git init
        /usr/bin/git remote add origin https://github.com/$u/$n
        ;;

      'gist')
        if [ -z "${p}" ]
          then 
            p=true
        fi

        if [ -z "${1}" ]
          then
            echo "'gist' requires a file"
            exit 1
          else
            declare -a ARGSV=($*)
            length=${#ARGSV[@]}
            for i in "${ARGSV[@]}"; do
              filename=${i##*/}
              data={\"description\":\"${d}\",\"public\":${p},\"files\":{\"$filename\":{\"content\":\"$(<$i)\"}}}
              rm -f .$filename
              echo $data > .$filename
              curl --request POST $url/gists --user $u --data @.$filename
              rm -f .$filename
            done
        fi
        ;;
    esac
fi